[features]
seeds = false
skip-lint = false

[programs.devnet]
forkit_escrow = "CNUWqYhXPXszPuB8psqG2VSnwCXf1MWzT4Pztp4y8fgj"
forkit_registry = "EM1FgSzfS3F7cCYJWhUaqqPAK7ijZYpYRx7pzYkuyExz"
forkit_loyalty = "BnnUntqkUadZ2BsW8j675P9hJQV3aqVcmt4xG4xfeoM8"
forkit_token = "FRKTkNq5sGhCVr3QLUwMGaznMaCvGkzNFbPmHd6XbC4q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
